### ISSUE TITLE
source code files in nighty builds are almost empty

### ISSUE THREAD

**Issue by BartolomeSintes** [subsurface/nightly-builds#1]
Hi,
The source code assets in [nighty builds page](https://github.com/subsurface/nightly-builds/releases)  are almost empty, both .zip and .tar.gz files. Should all the Subsurface source code be included in these files (per GPL 2 license)?
Best regards

**Comment by dirkhh** [comment]
This is a convenience repo, the sources are in the parallel one under subsurface/subsurface

But in order not to clutter our main repo with hundreds of tags, we use this one to stage the releases
